"""
Configuration settings for PathoAssist backend.
"""
from pathlib import Path
from typing import Optional
from pydantic_settings import BaseSettings


class Settings(BaseSettings):
    """Application settings and configuration."""

    # Application
    APP_NAME: str = "PathoAssist Backend"
    APP_VERSION: str = "1.0.0"
    DEBUG: bool = False

    # Server
    HOST: str = "127.0.0.1"
    PORT: int = 8000
    CORS_ORIGINS: list[str] = [
        "http://localhost:8080",
        "http://127.0.0.1:8080",
        "http://localhost:8006",
        "http://127.0.0.1:8006",
        "http://localhost:8007",
        "http://127.0.0.1:8007",
    ]

    # Storage
    BASE_DIR: Path = Path(__file__).parent.parent
    DATA_DIR: Path = BASE_DIR / "data"
    UPLOAD_DIR: Path = DATA_DIR / "uploads"
    CASES_DIR: Path = DATA_DIR / "cases"
    EXPORTS_DIR: Path = DATA_DIR / "exports"
    MODELS_DIR: Path = DATA_DIR / "models"
    LOGS_DIR: Path = DATA_DIR / "logs"

    # WSI Processing
    PATCH_SIZE: int = 224  # Standard patch size for medical imaging
    MAGNIFICATION: float = 20.0  # Default magnification level
    BACKGROUND_THRESHOLD: float = 0.8  # Threshold for background detection
    MIN_TISSUE_RATIO: float = 0.1  # Minimum tissue in patch
    MAX_PATCHES_PER_SLIDE: int = 1000  # Limit for performance

    # ROI Selection
    ROI_TOP_K: int = 50  # Number of top ROIs to auto-select
    ROI_VARIANCE_WEIGHT: float = 0.6  # Weight for color variance
    ROI_DENSITY_WEIGHT: float = 0.4  # Weight for tissue density

    # AI Inference
    MODEL_NAME: str = "google/medgemma-1.5-4b-it"  # Specialized Medical Model
    USE_QUANTIZATION: bool = True  # Enable 8-bit quantization
    MAX_TOKENS: int = 4096
    TEMPERATURE: float = 0.7
    TOP_P: float = 0.9
    DEVICE: str = "cpu"  # Will auto-detect GPU if available
    REMOTE_INFERENCE_URL: Optional[str] = None  # URL for remote inference (e.g. ngrok/colab)
    REMOTE_API_KEY: Optional[str] = None  # Optional API key for remote service

    # Safety & Compliance
    CONFIDENCE_THRESHOLD: float = 0.6  # Minimum confidence for findings
    ENABLE_DISCLAIMERS: bool = True
    LOG_ALL_INFERENCES: bool = True

    # Report Generation
    REPORT_TEMPLATE: str = "clinical"
    INCLUDE_CONFIDENCE_SCORES: bool = True
    MAX_REPORT_LENGTH: int = 2000

    # Export
    PDF_MARGIN: int = 50
    PDF_FONT_SIZE: int = 11

    class Config:
        env_file = ".env"
        case_sensitive = True


# Global settings instance
settings = Settings()


def init_directories():
    """Initialize required directories."""
    directories = [
        settings.DATA_DIR,
        settings.UPLOAD_DIR,
        settings.CASES_DIR,
        settings.EXPORTS_DIR,
        settings.MODELS_DIR,
        settings.LOGS_DIR,
    ]

    for directory in directories:
        directory.mkdir(parents=True, exist_ok=True)

    print(f"✓ Initialized directories at {settings.DATA_DIR}")


# Medical disclaimer template
MEDICAL_DISCLAIMER = """
IMPORTANT MEDICAL DISCLAIMER:
This report is generated by an AI-assisted system for research and decision support
purposes only. It is NOT intended for diagnostic use. All findings should be verified
by qualified healthcare professionals. This system does not replace professional
medical judgment, diagnosis, or treatment recommendations.
"""

# Forbidden diagnostic terms (to be filtered/flagged)
FORBIDDEN_DIAGNOSTIC_TERMS = [
    "diagnosed with",
    "definitive diagnosis",
    "confirmed diagnosis",
    "positively diagnosed",
    "conclusively shows",
]
